apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: xerobookz-dev

bases:
  - ../../base

patchesStrategicMerge:
  - deployment-patches.yaml

configMapGenerator:
  - name: xerobookz-config
    behavior: merge
    literals:
      - LOG_LEVEL=DEBUG
      - DEBUG=true

replicas:
  - name: auth-service
    count: 1
  - name: api-gateway
    count: 1

