apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: xerobookz

resources:
  - namespace.yaml
  - configmap.yaml
  - secrets.yaml
  - auth-service
  - user-service
  - organization-service
  - employee-service
  - document-service
  - i9-service
  - e-verify-service
  - i9-audit-service
  - paf-service
  - soc-predictor-service
  - immigration-service
  - lca-service
  - timesheet-service
  - leave-service
  - notification-service
  - audit-service
  - safety-service
  - onboarding-service
  - workflow-service
  - invoice-service
  - payment-service
  - finance-dashboard-service
  - marketing-service
  - ess-service
  - api-gateway

