apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: xerobookz-prod

bases:
  - ../../base

patchesStrategicMerge:
  - hpa-patches.yaml
  - pdb-patches.yaml

configMapGenerator:
  - name: xerobookz-config
    behavior: merge
    literals:
      - LOG_LEVEL=INFO
      - DEBUG=false

replicas:
  - name: auth-service
    count: 3
  - name: api-gateway
    count: 5

